sudo: false # Enable container-based infrastructure

language: scala
scala:
        - 2.10.4

# cache: apt # Enable caching on APT when it is available for our repo

os:
    - linux
    - osx

branches:
    only:
        - master
        - dev-master

env:
        - CCNL_HOME="/home/travis/build/cn-uofbasel/ccn-lite" PATH=$PATH:"$CCNL_HOME/bin" USE_NFN=1

addons:
    apt:
        packages:
            - libssl-dev
            - build-essential
            - pandoc
#            - linux-headers-$(uname -r)

install:
    - cd ..
    - git clone https://github.com/cn-uofbasel/ccn-lite.git
    - cd -

script:
    - cd $CCNL_HOME/src
    - pwd
    - echo $CCNL_HOME
    - echo ~  
    - make clean all
    - cd -
    - sbt compile
    - sbt 'runMain runnables.evaluation.WordcountApp' 
